/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * One Avro object container, addressable by record index.
 *
 * Records are reached by index without scanning the file, and writes buffer
 * per block so scattered edits cost one rewrite rather than one each.
 */
export declare class Avro {
  /**
   * Create an empty container and its header.
   *
   * `schema` is a `Schema`, or any declaration `parseSchema` accepts.
   */
  static create(schema: Schema | string | object, options?: CreateOptions | null): Avro
  /** Open an existing container image and index its blocks. */
  static open(data: Buffer, options?: OpenOptions | undefined | null): Avro
  /** Return the container's writer schema. */
  schema(): Schema
  /**
   * Return how many records the container holds, staged ones included.
   *
   * A method rather than a property: counting has to settle the staged
   * block first, which is work an innocent-looking `.length` should not do
   * behind a reader's back.
   */
  length(): number
  /** Return the block codec name. */
  get codec(): string
  /** Return the file's sync marker. */
  get syncMarker(): Buffer
  /** Return the staged-bytes threshold that closes a block. */
  get syncInterval(): number
  /** Return whether changes are staged but not yet in the image. */
  get dirty(): boolean
  /** Return the resident size of the image, index, and payload cache. */
  get nbytes(): number
  /** Return the container's header metadata. */
  metadata(): Record<string, Buffer>
  /** Decode one record by index. */
  get(index: number): unknown
  /** Decode a half-open record range. */
  range(start: number, stop: number): Array<unknown>
  /** Decode every record, in order. */
  toArray(): Array<unknown>
  /** Decode every record of one block. */
  readBlock(ordinal: number): Array<unknown>
  /** Encode one record onto the end of the container. */
  append(value: unknown): void
  /** Encode many records onto the end, framing whenever a block fills. */
  extend(values: Array<unknown>): void
  /** Replace one record. */
  set(index: number, value: unknown): void
  /** Replace the records in `[start, stop)` with `values`. */
  splice(start: number, stop: number, values: Array<unknown>): void
  /** Return every block's framing, located without decompressing it. */
  blocks(): Array<BlockInfo>
  /** Return the block that holds one record index. */
  blockOf(index: number): BlockInfo
  /** Re-frame every block at the current sync interval. */
  compact(): void
  /** Return the materialized container image, applying every pending change. */
  image(): Buffer
}

/**
 * One parsed Avro schema: its canonical form, its fingerprint, and the
 * encodings bound to it.
 *
 * The Rust name matches the JavaScript one on purpose: napi-rs keys its
 * class registry by the JS name but generates `instanceof` checks against the
 * Rust name, so a renamed class silently fails every `instanceof` test the
 * binding makes.
 */
export declare class Schema {
  /** Parse a schema from a JSON string or a plain object. */
  static parse(declaration: string | object): Schema
  /**
   * Return the schema's declaration as a plain JavaScript object.
   *
   * Named `toJSON` so `JSON.stringify(schema)` yields the declaration.
   */
  toJSON(): unknown
  /** Return the schema's declaration as JSON text. */
  json(): string
  /** Return the specification's parsing canonical form. */
  canonicalForm(): string
  /** Return the fully qualified name of the schema's root. */
  get fullname(): string
  /** Return the root's structural type name. */
  get typeName(): string
  /**
   * Return the 64-bit CRC-64-AVRO (Rabin) fingerprint of the canonical
   * form, as an **unsigned `bigint`**.
   *
   * The specification's vector for `"null"` is therefore
   * `0x63dd24e7cc258f8an`.  `fingerprintHex()` spells the same value as 16
   * lowercase hexadecimal digits when a string is easier to carry around.
   */
  fingerprint(): bigint
  /** Return the fingerprint as 16 lowercase hexadecimal digits. */
  fingerprintHex(): string
  /**
   * Return the Rabin fingerprint as the eight little-endian bytes Avro
   * writes into single-object framing.
   */
  fingerprintBytes(): Buffer
  /** Encode one value into Avro's binary representation. */
  encode(value: unknown): Buffer
  /** Decode one value from Avro's binary representation. */
  decode(data: Buffer): unknown
  /** Encode one value with Avro's single-object framing. */
  encodeSingleObject(value: unknown): Buffer
  /** Decode single-object framed data, validating its fingerprint. */
  decodeSingleObject(data: Buffer): unknown
  /**
   * Project one value into Avro's JSON encoding, as plain JavaScript data.
   *
   * Unions become the single-entry objects the specification asks for, and
   * bytes become Latin-1 strings — this is the interchange encoding, not
   * the natural JavaScript shape that [`Schema::decode`] returns.
   */
  toAvroJson(value: unknown): unknown
  /** Restore one value from Avro's JSON encoding. */
  fromAvroJson(value: unknown): unknown
  /** Return whether two schemas have the same canonical form. */
  equals(other: Schema): boolean
  /**
   * Print the schema as its canonical form.
   *
   * Spelled `to_display` in Rust because an inherent `to_string` shadows
   * `Display`; JavaScript still sees the `toString` it expects.
   */
  toString(): string
}

/** One container block's framing, located without decompressing its payload. */
export interface BlockInfo {
  ordinal: number
  offset: number
  dataOffset: number
  size: number
  count: number
  first: number
}

/** Return every block codec the container supports. */
export declare function codecs(): Array<string>

/** Return the container constants JavaScript needs to frame blocks itself. */
export declare function constants(): Constants

/** The container format's fixed sizes and markers. */
export interface Constants {
  syncSize: number
  defaultSyncInterval: number
  randomSyncInterval: number
  defaultCacheBytes: number
  magic: Buffer
}

/** Return the core crate's version, for diagnostics. */
export declare function coreVersion(): string

/** Options for a new container. */
export interface CreateOptions {
  /** Block codec: `null`, `deflate`, `bzip2`, or `xz`. */
  codec?: string
  /**
   * Extra header metadata; `avro.schema` and `avro.codec` are owned by the
   * container itself and are ignored here.
   */
  metadata?: Record<string, string>
  /** The 16-byte sync marker, random by default. */
  syncMarker?: Buffer
  /** The staged-bytes threshold that closes a block. */
  syncInterval?: number
}

/** Options for opening an existing container. */
export interface OpenOptions {
  /** The staged-bytes threshold used when framing new blocks. */
  syncInterval?: number
  /** The decoded-payload cache budget, in bytes. */
  cacheBytes?: number
}

/**
 * Parse an Avro schema from a JSON string or a plain JavaScript object.
 *
 * Objects are read exactly as `JSON.parse` would have produced them, so
 * `parseSchema(require('./user.avsc'))` and
 * `parseSchema(readFileSync('user.avsc', 'utf8'))` agree.
 */
export declare function parseSchema(declaration: string | object): Schema

/** Return the Rabin fingerprint of arbitrary bytes. */
export declare function rabin(payload: Buffer): bigint

/**
 * Hand the addon the JavaScript error classes it throws.
 *
 * `js/index.js` calls this once, at require time; see `errors.rs` for why the
 * classes live in JavaScript rather than being synthesized here.
 */
export declare function registerErrorClasses(base: unknown, schema: unknown, encode: unknown, decode: unknown): void
