'use strict'

/**
 * `@rkp/avro` — the JavaScript face of the `rkp-avro` Rust core.
 *
 * Everything with behaviour lives in the napi addon built from
 * `rust/crates/rkp-avro-node`. `binding.js` is generated by `@napi-rs/cli`
 * (`npm run build`); it does the platform detection and `require()`s the right
 * `rkp-avro.<triple>.node`. Do not hand-edit `binding.js` or `binding.d.ts`.
 *
 * Two things are genuinely JavaScript rather than Rust, and both live here:
 *
 *  - the error classes, so `instanceof` works and users can subclass them;
 *  - the export table, written as literal `module.exports.<name> = ...`
 *    statements. Node's ESM loader discovers a CommonJS module's named
 *    exports with `cjs-module-lexer`, which only recognises static
 *    assignments — building the table from a loop or an array of names
 *    silently breaks `import { parseSchema } from '@rkp/avro'`. Keep it
 *    boring.
 */

const native = require('./binding.js')

/* ------------------------------------------------------------------------ *
 * Errors.
 *
 * The addon decides which class every failure is and throws an instance of
 * these; see `rust/crates/rkp-avro-node/src/errors.rs`. Declaring them here
 * rather than synthesizing them in Rust keeps them ordinary, subclassable
 * `Error`s with a real prototype chain and a usable stack.
 * ------------------------------------------------------------------------ */

/** Base class for every Avro failure, and the class of container failures. */
class AvroError extends Error {
  constructor(message) {
    super(message)
    this.name = 'AvroError'
  }
}

/** An Avro schema is malformed, unknown, or internally inconsistent. */
class AvroSchemaError extends AvroError {
  constructor(message) {
    super(message)
    this.name = 'AvroSchemaError'
  }
}

/** A value cannot be encoded against its declared Avro schema. */
class AvroEncodeError extends AvroError {
  constructor(message) {
    super(message)
    this.name = 'AvroEncodeError'
  }
}

/** Encoded Avro data is truncated or inconsistent with its schema. */
class AvroDecodeError extends AvroError {
  constructor(message) {
    super(message)
    this.name = 'AvroDecodeError'
  }
}

/**
 * Pull a symbol out of the addon, failing loudly instead of exporting
 * `undefined` if the built `.node` is stale or mismatched.
 *
 * @param {string} name
 * @returns {unknown}
 */
function fromNative(name) {
  const value = native[name]
  if (value === undefined) {
    throw new Error(
      `@rkp/avro: the native addon does not export '${name}'. The built ` +
        `.node file is stale or does not match this package — re-run ` +
        `\`npm run build\` in the js/ directory.`,
    )
  }
  return value
}

fromNative('registerErrorClasses')(
  AvroError,
  AvroSchemaError,
  AvroEncodeError,
  AvroDecodeError,
)

module.exports.AvroError = AvroError
module.exports.AvroSchemaError = AvroSchemaError
module.exports.AvroEncodeError = AvroEncodeError
module.exports.AvroDecodeError = AvroDecodeError

/* ------------------------------------------------------------------------ *
 * The Avro surface.
 * ------------------------------------------------------------------------ */

/**
 * Parse an Avro schema from a JSON string or a plain object.
 *
 * @type {(declaration: string | object) => import('./binding.js').Schema}
 */
module.exports.parseSchema = fromNative('parseSchema')

/**
 * A parsed Avro schema: canonical form, fingerprint, and the codecs bound to
 * it. Construct one with {@link module.exports.parseSchema} or `Schema.parse`.
 */
module.exports.Schema = fromNative('Schema')

/** One Avro object container file, addressable by record index. */
module.exports.Avro = fromNative('Avro')

/**
 * The CRC-64-AVRO (Rabin) fingerprint of arbitrary bytes, as a `bigint`.
 *
 * @type {(payload: Buffer) => bigint}
 */
module.exports.rabin = fromNative('rabin')

/**
 * Every block codec the container implementation supports.
 *
 * @type {() => string[]}
 */
module.exports.codecs = fromNative('codecs')

/**
 * The container format's fixed sizes and markers.
 *
 * @type {() => import('./binding.js').Constants}
 */
module.exports.constants = fromNative('constants')

/**
 * The `rkp-avro` core crate's version, for diagnostics.
 *
 * @type {() => string}
 */
module.exports.coreVersion = fromNative('coreVersion')
