[package]
name = "rkp-avro"
description = "Apache Avro schemas, binary data, and random-access container files"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
serde_json.workspace = true
flate2.workspace = true
bzip2.workspace = true
liblzma.workspace = true
